*-- Note: Code used in the examination of data, but not final modelling, is also included here to demonstrate other avenues that were examined before choosing best fit;

ods graphics on;
ods rtf file = 'AbandonedCars.rtf';
proc means data = work.cars maxdec = 1;
class OutOfState;
run;
proc means data =  work.cars maxdec = 1;
class MakerCode;
run;
proc means data =  work.cars maxdec = 1;
class Color_Code;
run;
proc means data =  work.cars maxdec = 1;
class ActionCode;
run;
proc means data =  work.cars maxdec = 1;
class MainThoroughfare;
run;
proc means data =  work.cars maxdec = 1;
class Transit_Code;
run;
proc means data = work.cars n mean stddev median maxdec = 1 skew;
var  ComplaintActiveTime DaysParked;
run;
proc freq data = work.cars;
Tables MakerCode OutOfState Color_Code MakerCode*OutOfState OutOfState*Color_Code MakerCode*Color_Code / nocum chisq expected cellchi2 riskdiff cmh1;
run;
proc freq data = work.cars;
Tables ActionCode*Transit_Code /chisq cmh1 trend;
run;
proc genmod data = work.cars;
model ComplaintActiveTime = Color_Code DaysParked Transit_Code OutOfState MainThoroughfare MakerCode/ dist = poi link = identity;
run;
proc genmod data = work.cars;
model ComplaintActiveTime = Color_Code DaysParked Transit_Code OutOfState MainThoroughfare MakerCode/ dist = poi link = log;
run;
proc genmod data = work.cars;
model ComplaintActiveTime = Color_Code DaysParked Transit_Code OutOfState MainThoroughfare MakerCode/ dist = negbin link = log;
run;
proc logistic descending data = work.cars;
model ComplaintActiveTime = Color_Code DaysParked Transit_Code OutOfState MainThoroughfare MakerCode;
run;
proc logistic descending data = work.cars;
model ComplaintActiveTime = Color_Code DaysParked Transit_Code OutOfState MainThoroughfare MakerCode/selection = forward details lackfit;
run;
proc logistic descending data = work.cars;
model ComplaintActiveTime = Color_Code DaysParked Transit_Code OutOfState MainThoroughfare MakerCode/ctable pprob = (0 to 1 by .1) lackfit risklimits;
run;
proc logistic descending data = work.cars;
model ComplaintActiveTime = Color_Code DaysParked OutOfState MainThoroughfare MakerCode;
units How_Many_Days_Has_the_Vehicle_Be = 7;
run;
proc logistic descending data = work.cars;
model ComplaintActiveTime = Color_Code How_Many_Days_Has_the_Vehicle_Be Transit_Code OutOfState MainThoroughfare MakerCode
DaysParked*Transit_Code DaysParked*Color_Code DaysParked*OutOfState DaysParked*MainThoroughfare
Color_Code * Transit_Code Color_Code*OutOfState Color_Code*MainThoroughfare
Transit_Code*OutOfState Transit_Code*MainThoroughfare OutOfState*MainThoroughfare
MakerCode * Color_Code MakerCode*Transit_Code MakerCode*OutOfState MakerCode*MainThoroughfare MakerCode*DaysParked
/selection = forward include = 3 details lackfit;
run;
proc logistic descending data = work.cars;
Class Color_code OutOfState MainThoroughfare MakerCode;
model ComplaintActiveTime = Color_Code MakerCode DaysParked Transit_Code OutOfState MainThoroughfare/ selection=backward lackfit;
run;
 proc catmod data = work.cars;
      model Vehicle_Code*Color_Code=_response_ / noiter;
      loglin Vehicle_Code|Color_Code;
   run;
   proc catmod data = work.cars;
      model MakerCode*Color_Code=_response_ / noiter;
      loglin MakerCode Color_Code;
   run;
    proc catmod data = work.cars;
      model OutOfState*MainThoroughfare=_response_ / noiter;
      loglin OutOfState|MainThoroughfare;
   run;
    proc catmod data = work.cars;
      model MakerCode*Transit_Code=_response_ / noiter;
      loglin MakerCode|Transit_Code;
   run;
ods graphics off;
ods rtf close;
run;
